---
dist: xenial

before_install:
  - pyenv global system 3.6.7
  - sudo apt-get update
  - sudo apt-get install -y tidy
# before_install:
install:
#   - pip install -r requirements/dev.txt
  - pip3 install pytest pycodestyle
# script:
#   - coverage run -m pytest

# before_install:
#   - docker build -t erseco/ugr_tfm_maes .


script:
  - echo "Testing that we have all the requirements"
  - python3 --version
  - ruby --version
  - gcc --version
  - tidy --version

  - pycodestyle homework_01_python/*.py
  - pytest --verbose homework_01_python/*.py

  - tidy -quiet -errors homework_04_html/*.html
