---
dist: xenial

before_install:
  - pyenv global system 3.6.7
  - sudo apt-get update
  - sudo apt-get install -y tidy cppcheck
install:
  - pip3 install pytest pycodestyle requests beautifulsoup4
  - gem install rspec rubocop mdl

script:
  - echo "Testing that we have all the requirements"
  - mdl --version
  - python3 --version
  - ruby --version
  - gcc --version
  - tidy --version

  - mdl homework_00_git/

  - pycodestyle homework_01_python/*.py
  - pytest --verbose homework_01_python/*.py

  - rubocop homework_02_ruby
  - rspec homework_02_ruby

  - cppcheck --verbose --error-exitcode=2 homework_03_c/*.c
  - cd homework_03_c && make tests

  - tidy -quiet -errors homework_04_html/*.html
